apiVersion: v2
name: common
description: Library of Common Templates for Cribl Helm Charts for Kubernetes
maintainers:
  - name: Cribl, Inc.
    email: support@cribl.io
    url: https://github.com/criblio/helm-charts
type: library
version: 4.12.1
appVersion: 4.12.1
